//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Categorie
{
	public virtual string _nomCaterogie
	{
		get;
		set;
	}

	public virtual IEnumerable<Activite> listeActivite
	{
		get;
		set;
	}

	public Categorie(string unNom)
	{
	}

}

