//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Activite
{
    private List<Astronaute> tableauAstronautes;

    public List<Astronaute> mesAstronautes {
        get { return tableauAstronautes; }
        set { tableauAstronautes = value; }
    }
    



	public virtual DateTime _debutTache
	{
		get;
		set;
	}

	public virtual DateTime _finTache
	{
		get;
		set;
	}

	public virtual string _nomTache
	{
		get;
		set;
	}

	public virtual bool _exterieur
	{
		get;
		set;
	}

	public virtual string _description
	{
		get;
		set;
	}

	public virtual string _nomIcone
	{
		get;
		set;
	}

	public Activite(string unNom, bool boolExt, string uneDesc, DateTime unDebut, DateTime uneFin, string uneIcone)
	{
	}

}

