//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Journee
{
	public virtual int _numero
	{
		get;
		set;
	}

	public virtual string _etat
	{
		get;
		set;
	}

	public virtual string _compteRendu
	{
		get;
		set;
	}

	public virtual IEnumerable<Activite> listeActivites
	{
		get;
		set;
	}

	public Journee(int unNumero)
	{
	}

}

