//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Lieu
{
	public virtual string _nomLieu
	{
		get;
		set;
	}

	public virtual Double _posXLieu
	{
		get;
		set;
	}

	public virtual Double _posYLieu
	{
		get;
		set;
	}

	public virtual Double[] getCoordonnees()
	{
		throw new System.NotImplementedException();
	}

	public Lieu(string unNom, Double unePosX, Double unePosY)
	{
	}

}

