//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Map
{
	public virtual string _nomMap
	{
		get;
		set;
	}

	public virtual Double _longueur
	{
		get;
		set;
	}

	public virtual Double _largueur
	{
		get;
		set;
	}

	public Map(string UneImage)
	{
	}

}

